# Ultralytics dataset config template
# Update 'path' to your dataset folder (Drive or local).
path: ../dataset

train: train/images
val: val/images
test: test/images
# Classes
nc: 6
names: ['bus', 'car', 'matatu', 'motorcycle', 'number_plate', 'truck']
